[package]
name = "selim"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
assert_approx_eq = "1.1.0"
midi-reader-writer = { version = "0.1.0", features = ["engine-midly-0-5"] }
midly = "0.5"
